name: Build Mobile Apps

on:
  # Runs on pushes targeting the default branch
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build Vue.js project
      run: npm run build

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova project
      run: cordova create cordova com.phillweston.rubao Rubao

    - name: Copy Vue.js build to Cordova project
      run: cp -r dist/* cordova/www/

    - name: Add Android platform to Cordova project
      run: |
        cd cordova
        cordova platform add android

    - name: Build Android app
      run: |
        cd cordova
        cordova build android --release -- --packageType=apk 

    - name: Prepare artifacts directory
      run: |
        mkdir -p artifacts/android-app
        cp cordova/platforms/android/app/build/outputs/apk/release/app-release.apk artifacts/android-app/Rubao-${{ github.ref_name }}.apk

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: artifacts/android-app/Rubao-${{ github.ref_name }}.apk

  release:
    needs: [build-android]
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Android APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/android-app/Rubao-${{ github.ref_name }}.apk
        asset_name: Rubao-${{ github.ref_name }}.apk
        asset_content_type: application/vnd.android.package-archive